"""
Slab Peripherals - LLM-Friendly Peripheral Auto-Generator

This module provides automatic peripheral model generation based on
observed I/O patterns. Designed to be used by LLMs to implement
missing peripherals dynamically as code evolves.

Features:
- I/O pattern detection and classification
- Automatic register behavior inference
- LLM-readable descriptions of observed patterns
- Code generation for peripheral models
- Dynamic update as firmware behavior changes

Dual-licensed for maximum compatibility:
- SPDX-License-Identifier: Apache-2.0 OR Apache-2.0

Author: Mathieu Renard <mathieu.renard@twistedwires.io>
Copyright (C) 2026 Twisted Wires Security Lab

This file is distributed under a dual license:
  - GPL-3.0-or-later (for GPL-compatible projects)
  - Apache-2.0 (for Apache-compatible projects like Wookey)
You may choose either license.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, Tuple, Set
from enum import IntEnum, auto
import time
import json
from collections import defaultdict


class AccessType(IntEnum):
    """Type of memory access."""
    READ = 0
    WRITE = 1


class RegisterBehavior(IntEnum):
    """Inferred register behavior."""
    UNKNOWN = 0             # Not enough data
    STATUS = 1              # Read-only, changes over time
    CONTROL = 2             # Write to configure, read back same
    DATA = 3                # Data buffer (FIFO-like)
    CLEAR_ON_READ = 4       # Value clears when read
    WRITE_ONLY = 5          # Write only, reads return 0/const
    READ_ONLY_CONST = 6     # Always returns same value
    COUNTER = 7             # Increments automatically
    INTERRUPT_STATUS = 8    # Bit fields, write-1-to-clear
    SET_CLEAR = 9           # Separate set/clear registers


@dataclass
class IOAccess:
    """Record of a single I/O access."""
    timestamp: float
    cycle: int
    pc: int
    address: int
    size: int
    access_type: AccessType
    value: int
    prev_value: int = 0     # Value before write, or previous read


@dataclass
class IOPattern:
    """Detected I/O access pattern for a register."""
    address: int
    name: str = ""
    offset: int = 0
    size: int = 4

    # Access statistics
    read_count: int = 0
    write_count: int = 0
    unique_read_values: Set[int] = field(default_factory=set)
    unique_write_values: Set[int] = field(default_factory=set)

    # Pattern detection
    inferred_behavior: RegisterBehavior = RegisterBehavior.UNKNOWN
    confidence: float = 0.0

    # Bit field analysis
    set_bits: int = 0       # Bits ever set to 1
    clear_bits: int = 0     # Bits ever set to 0
    toggle_bits: int = 0    # Bits that change

    # Timing analysis
    first_access: float = 0
    last_access: float = 0
    avg_read_interval: float = 0
    avg_write_interval: float = 0

    # Access patterns
    read_after_write: int = 0   # Count of reads following writes
    poll_count: int = 0         # Repeated reads (polling)
    write_sequences: List[List[int]] = field(default_factory=list)

    def describe(self) -> str:
        """Get LLM-readable description of this pattern."""
        lines = [
            f"Register at 0x{self.address:08X} ({self.name or 'unknown'}):",
            f"  Behavior: {self.inferred_behavior.name} (confidence: {self.confidence:.0%})",
            f"  Reads: {self.read_count}, Writes: {self.write_count}",
            f"  Unique read values: {len(self.unique_read_values)}",
            f"  Unique write values: {len(self.unique_write_values)}",
        ]

        if self.inferred_behavior == RegisterBehavior.STATUS:
            lines.append(f"  -> Likely a status register (polled frequently)")
        elif self.inferred_behavior == RegisterBehavior.CONTROL:
            lines.append(f"  -> Likely a control register (configured then read back)")
        elif self.inferred_behavior == RegisterBehavior.DATA:
            lines.append(f"  -> Likely a data register (many unique values)")
        elif self.inferred_behavior == RegisterBehavior.INTERRUPT_STATUS:
            lines.append(f"  -> Likely interrupt status (bit fields, write-1-to-clear)")

        if self.toggle_bits:
            lines.append(f"  Active bits: 0x{self.toggle_bits:08X}")

        return "\n".join(lines)


@dataclass
class PeripheralTemplate:
    """Template for generating peripheral code."""
    base_address: int
    name: str
    size: int
    registers: List[IOPattern] = field(default_factory=list)

    def to_python(self) -> str:
        """Generate Python peripheral model code."""
        lines = [
            f'"""',
            f'Auto-generated peripheral model for {self.name}',
            f'Base address: 0x{self.base_address:08X}',
            f'Generated by Slab PeripheralGenerator',
            f'"""',
            '',
            f'class {self.name}Peripheral:',
            f'    """Peripheral model for {self.name}."""',
            '',
            f'    BASE_ADDR = 0x{self.base_address:08X}',
            f'    SIZE = 0x{self.size:X}',
            '',
            '    # Register offsets',
        ]

        for reg in self.registers:
            offset = reg.address - self.base_address
            name = reg.name or f"REG_{offset:02X}"
            lines.append(f'    {name.upper()} = 0x{offset:02X}')

        lines.extend([
            '',
            '    def __init__(self):',
            '        """Initialize peripheral state."""',
            '        self.registers = {}',
        ])

        for reg in self.registers:
            offset = reg.address - self.base_address
            name = reg.name or f"REG_{offset:02X}"
            lines.append(f'        self.registers[0x{offset:02X}] = 0  # {name}')

        lines.extend([
            '',
            '    def read(self, offset: int, size: int) -> int:',
            '        """Handle read access."""',
            '        value = self.registers.get(offset, 0)',
        ])

        # Add behavior-specific read handling
        for reg in self.registers:
            offset = reg.address - self.base_address
            if reg.inferred_behavior == RegisterBehavior.CLEAR_ON_READ:
                lines.extend([
                    f'        if offset == 0x{offset:02X}:',
                    f'            self.registers[0x{offset:02X}] = 0  # Clear on read',
                ])

        lines.extend([
            '        return value',
            '',
            '    def write(self, offset: int, value: int, size: int) -> None:',
            '        """Handle write access."""',
        ])

        # Add behavior-specific write handling
        for reg in self.registers:
            offset = reg.address - self.base_address
            if reg.inferred_behavior == RegisterBehavior.INTERRUPT_STATUS:
                lines.extend([
                    f'        if offset == 0x{offset:02X}:',
                    f'            # Write-1-to-clear for interrupt status',
                    f'            self.registers[0x{offset:02X}] &= ~value',
                    f'            return',
                ])

        lines.extend([
            '        self.registers[offset] = value',
        ])

        return '\n'.join(lines)

    def to_c(self) -> str:
        """Generate C peripheral model code (QEMU style)."""
        lines = [
            '/*',
            f' * Auto-generated peripheral model for {self.name}',
            f' * Base address: 0x{self.base_address:08X}',
            ' * Generated by Slab PeripheralGenerator',
            ' *',
            ' * SPDX-License-Identifier: Apache-2.0 OR Apache-2.0',
            ' */',
            '',
            '#include "qemu/osdep.h"',
            '#include "hw/sysbus.h"',
            '#include "qemu/log.h"',
            '',
            f'#define TYPE_{self.name.upper()} "{self.name.lower()}"',
            f'#define {self.name.upper()}(obj) \\',
            f'    OBJECT_CHECK({self.name}State, (obj), TYPE_{self.name.upper()})',
            '',
            '/* Register offsets */',
        ]

        for reg in self.registers:
            offset = reg.address - self.base_address
            name = reg.name or f"REG_{offset:02X}"
            lines.append(f'#define {name.upper()}_OFFSET 0x{offset:02X}')

        lines.extend([
            '',
            f'typedef struct {self.name}State {{',
            '    SysBusDevice parent_obj;',
            '    MemoryRegion iomem;',
            '',
        ])

        for reg in self.registers:
            offset = reg.address - self.base_address
            name = reg.name or f"reg_{offset:02x}"
            lines.append(f'    uint32_t {name.lower()};')

        lines.extend([
            f'}} {self.name}State;',
            '',
            f'static uint64_t {self.name.lower()}_read(void *opaque, hwaddr offset, unsigned size)',
            '{',
            f'    {self.name}State *s = {self.name.upper()}(opaque);',
            '',
            '    switch (offset) {',
        ])

        for reg in self.registers:
            offset = reg.address - self.base_address
            name = reg.name or f"reg_{offset:02x}"
            lines.extend([
                f'    case 0x{offset:02X}:',
                f'        return s->{name.lower()};',
            ])

        lines.extend([
            '    default:',
            '        qemu_log_mask(LOG_UNIMP, "%s: unimplemented read at 0x%lx\\n",',
            f'                      __func__, (unsigned long)offset);',
            '        return 0;',
            '    }',
            '}',
            '',
            f'static void {self.name.lower()}_write(void *opaque, hwaddr offset,',
            '                                   uint64_t value, unsigned size)',
            '{',
            f'    {self.name}State *s = {self.name.upper()}(opaque);',
            '',
            '    switch (offset) {',
        ])

        for reg in self.registers:
            offset = reg.address - self.base_address
            name = reg.name or f"reg_{offset:02x}"
            lines.extend([
                f'    case 0x{offset:02X}:',
                f'        s->{name.lower()} = value;',
                '        break;',
            ])

        lines.extend([
            '    default:',
            '        qemu_log_mask(LOG_UNIMP, "%s: unimplemented write at 0x%lx\\n",',
            f'                      __func__, (unsigned long)offset);',
            '    }',
            '}',
            '',
            f'static const MemoryRegionOps {self.name.lower()}_ops = {{',
            f'    .read = {self.name.lower()}_read,',
            f'    .write = {self.name.lower()}_write,',
            '    .endianness = DEVICE_LITTLE_ENDIAN,',
            '};',
        ])

        return '\n'.join(lines)


class PeripheralGenerator:
    """
    LLM-friendly peripheral auto-generator.

    Watches I/O patterns during emulation and infers peripheral
    behavior. Can generate code for missing peripherals.

    LLM Integration:
    - `describe_all_patterns()` returns complete I/O analysis
    - `suggest_peripheral()` recommends peripheral implementation
    - `generate_code()` produces working peripheral code
    - `update_from_access()` learns from new I/O events

    Example:
        gen = PeripheralGenerator()

        # Feed I/O events from emulator
        gen.update_from_access(0x40020000, 4, AccessType.READ, 0x00000001, pc=0x08001234)
        gen.update_from_access(0x40020004, 4, AccessType.WRITE, 0x00000003, pc=0x08001238)

        # Get LLM-readable analysis
        print(gen.describe_all_patterns())

        # Generate peripheral code
        code = gen.generate_peripheral("GPIO", 0x40020000, 0x400)
    """

    def __init__(self, min_accesses: int = 5):
        """
        Initialize peripheral generator.

        Args:
            min_accesses: Minimum accesses before inferring behavior
        """
        self.accesses: List[IOAccess] = []
        self.patterns: Dict[int, IOPattern] = {}
        self.min_accesses = min_accesses
        self.cycle_count = 0

        # Known peripheral regions (for naming)
        self.known_regions: Dict[Tuple[int, int], str] = {}

        # Register value tracking
        self.register_values: Dict[int, int] = defaultdict(int)

    def add_known_region(self, base: int, size: int, name: str) -> None:
        """Add a known peripheral region for naming."""
        self.known_regions[(base, size)] = name

    def update_from_access(
        self,
        address: int,
        size: int,
        access_type: AccessType,
        value: int,
        pc: int = 0,
        cycle: int = None,
    ) -> None:
        """
        Update patterns from an I/O access.

        Call this for every peripheral read/write during emulation.
        """
        if cycle is None:
            cycle = self.cycle_count
        self.cycle_count = cycle + 1

        prev_value = self.register_values[address]

        access = IOAccess(
            timestamp=time.time(),
            cycle=cycle,
            pc=pc,
            address=address,
            size=size,
            access_type=access_type,
            value=value,
            prev_value=prev_value,
        )
        self.accesses.append(access)

        # Update current value
        if access_type == AccessType.WRITE:
            self.register_values[address] = value

        # Update pattern
        self._update_pattern(access)

    def _update_pattern(self, access: IOAccess) -> None:
        """Update pattern for a register."""
        addr = access.address

        if addr not in self.patterns:
            self.patterns[addr] = IOPattern(
                address=addr,
                size=access.size,
                first_access=access.timestamp,
            )

        pattern = self.patterns[addr]
        pattern.last_access = access.timestamp

        if access.access_type == AccessType.READ:
            pattern.read_count += 1
            pattern.unique_read_values.add(access.value)
        else:
            pattern.write_count += 1
            pattern.unique_write_values.add(access.value)

        # Track bit activity
        pattern.set_bits |= access.value
        pattern.clear_bits |= ~access.value & 0xFFFFFFFF

        # Detect toggling bits
        if access.prev_value != 0:
            pattern.toggle_bits |= access.value ^ access.prev_value

        # Check for polling pattern
        if len(self.accesses) >= 2:
            prev = self.accesses[-2]
            if (prev.address == addr and
                prev.access_type == AccessType.READ and
                access.access_type == AccessType.READ):
                pattern.poll_count += 1

            if (prev.address == addr and
                prev.access_type == AccessType.WRITE and
                access.access_type == AccessType.READ):
                pattern.read_after_write += 1

        # Infer behavior
        self._infer_behavior(pattern)

    def _infer_behavior(self, pattern: IOPattern) -> None:
        """Infer register behavior from observed patterns."""
        total = pattern.read_count + pattern.write_count
        if total < self.min_accesses:
            pattern.inferred_behavior = RegisterBehavior.UNKNOWN
            pattern.confidence = 0.0
            return

        # Calculate ratios
        read_ratio = pattern.read_count / total if total > 0 else 0
        write_ratio = pattern.write_count / total if total > 0 else 0

        # Status register: mostly reads, value changes
        if read_ratio > 0.8 and len(pattern.unique_read_values) > 3:
            if pattern.poll_count > pattern.read_count * 0.5:
                pattern.inferred_behavior = RegisterBehavior.STATUS
                pattern.confidence = min(0.9, 0.5 + pattern.poll_count / 100)
                return

        # Control register: mostly writes, some read-back
        if write_ratio > 0.6 and pattern.read_after_write > 0:
            pattern.inferred_behavior = RegisterBehavior.CONTROL
            pattern.confidence = min(0.9, 0.5 + write_ratio * 0.4)
            return

        # Data register: many unique values
        unique_ratio = len(pattern.unique_read_values | pattern.unique_write_values) / total
        if unique_ratio > 0.5:
            pattern.inferred_behavior = RegisterBehavior.DATA
            pattern.confidence = min(0.9, unique_ratio)
            return

        # Write-only: no reads
        if pattern.read_count == 0 and pattern.write_count > 0:
            pattern.inferred_behavior = RegisterBehavior.WRITE_ONLY
            pattern.confidence = 0.8
            return

        # Read-only constant: always same value
        if len(pattern.unique_read_values) == 1 and pattern.write_count == 0:
            pattern.inferred_behavior = RegisterBehavior.READ_ONLY_CONST
            pattern.confidence = min(0.9, 0.5 + pattern.read_count / 20)
            return

        # Interrupt status: bitfield patterns
        if pattern.toggle_bits and bin(pattern.toggle_bits).count('1') >= 2:
            # Check for write-1-to-clear pattern
            for val in pattern.unique_write_values:
                if val == pattern.toggle_bits or bin(val).count('1') <= 3:
                    pattern.inferred_behavior = RegisterBehavior.INTERRUPT_STATUS
                    pattern.confidence = 0.7
                    return

        pattern.inferred_behavior = RegisterBehavior.UNKNOWN
        pattern.confidence = 0.3

    def describe_all_patterns(self) -> str:
        """
        Get LLM-readable description of all detected patterns.

        Use this to understand what the firmware is doing with peripherals.
        """
        lines = [
            "=" * 60,
            "Peripheral I/O Pattern Analysis",
            "=" * 60,
            f"Total accesses recorded: {len(self.accesses)}",
            f"Unique registers: {len(self.patterns)}",
            "",
        ]

        # Group by peripheral region
        regions: Dict[str, List[IOPattern]] = defaultdict(list)
        for pattern in sorted(self.patterns.values(), key=lambda p: p.address):
            region_name = self._get_region_name(pattern.address)
            regions[region_name].append(pattern)

        for region, patterns in regions.items():
            lines.append(f"\n{region}:")
            lines.append("-" * 40)

            for pattern in patterns:
                lines.append(pattern.describe())
                lines.append("")

        return "\n".join(lines)

    def _get_region_name(self, address: int) -> str:
        """Get name for a peripheral region."""
        for (base, size), name in self.known_regions.items():
            if base <= address < base + size:
                return name

        # STM32 common regions
        if 0x40000000 <= address < 0x40008000:
            return "APB1 Peripherals"
        elif 0x40010000 <= address < 0x40015000:
            return "APB2 Peripherals"
        elif 0x40020000 <= address < 0x40024000:
            return "AHB1 Peripherals (GPIO)"
        elif 0x40023800 <= address < 0x40023C00:
            return "RCC"
        elif 0xE0000000 <= address < 0xF0000000:
            return "System Control Space"

        return f"Unknown Region (0x{address & 0xFFF00000:08X})"

    def suggest_peripheral(self, base_address: int, size: int = 0x100) -> str:
        """
        Suggest peripheral implementation based on patterns.

        Returns LLM-readable suggestion with code snippets.
        """
        # Find patterns in this region
        region_patterns = [
            p for p in self.patterns.values()
            if base_address <= p.address < base_address + size
        ]

        if not region_patterns:
            return f"No I/O patterns detected in region 0x{base_address:08X}-0x{base_address+size:08X}"

        lines = [
            f"Peripheral Suggestion for 0x{base_address:08X}:",
            "=" * 50,
            "",
            "Detected registers:",
        ]

        for p in sorted(region_patterns, key=lambda x: x.address):
            offset = p.address - base_address
            lines.append(f"  0x{offset:02X}: {p.inferred_behavior.name}")

            if p.inferred_behavior == RegisterBehavior.STATUS:
                lines.append(f"       -> Implement as status register (return dynamic value)")
            elif p.inferred_behavior == RegisterBehavior.CONTROL:
                lines.append(f"       -> Implement as control register (store value)")
            elif p.inferred_behavior == RegisterBehavior.DATA:
                lines.append(f"       -> Implement as data register (FIFO or buffer)")

        lines.extend([
            "",
            "Recommended implementation:",
            "```python",
        ])

        # Generate code suggestion
        template = self.generate_peripheral("Peripheral", base_address, size)
        lines.append(template.to_python())
        lines.append("```")

        return "\n".join(lines)

    def generate_peripheral(
        self,
        name: str,
        base_address: int,
        size: int,
    ) -> PeripheralTemplate:
        """
        Generate peripheral template from detected patterns.

        Returns PeripheralTemplate that can generate Python or C code.
        """
        region_patterns = [
            p for p in self.patterns.values()
            if base_address <= p.address < base_address + size
        ]

        # Assign names to registers
        for i, p in enumerate(sorted(region_patterns, key=lambda x: x.address)):
            if not p.name:
                offset = p.address - base_address
                if p.inferred_behavior == RegisterBehavior.STATUS:
                    p.name = f"STATUS_{i}"
                elif p.inferred_behavior == RegisterBehavior.CONTROL:
                    p.name = f"CTRL_{i}"
                elif p.inferred_behavior == RegisterBehavior.DATA:
                    p.name = f"DATA_{i}"
                else:
                    p.name = f"REG_{offset:02X}"

        return PeripheralTemplate(
            base_address=base_address,
            name=name,
            size=size,
            registers=region_patterns,
        )

    def get_unhandled_accesses(self) -> List[Tuple[int, int, str]]:
        """
        Get list of unhandled peripheral accesses.

        Returns list of (address, count, suggestion) tuples.
        """
        result = []
        for pattern in self.patterns.values():
            if pattern.inferred_behavior == RegisterBehavior.UNKNOWN:
                total = pattern.read_count + pattern.write_count
                result.append((
                    pattern.address,
                    total,
                    f"Unknown register with {total} accesses"
                ))
        return sorted(result, key=lambda x: -x[1])

    def export_patterns(self, path: str) -> None:
        """Export patterns to JSON for LLM analysis."""
        data = {
            "total_accesses": len(self.accesses),
            "patterns": [
                {
                    "address": p.address,
                    "name": p.name,
                    "read_count": p.read_count,
                    "write_count": p.write_count,
                    "behavior": p.inferred_behavior.name,
                    "confidence": p.confidence,
                    "unique_read_values": list(p.unique_read_values)[:10],
                    "unique_write_values": list(p.unique_write_values)[:10],
                }
                for p in self.patterns.values()
            ]
        }
        with open(path, 'w') as f:
            json.dump(data, f, indent=2)
